### ISSUE TITLE
How about use a template engine?

### ISSUE THREAD

**Issue by iblancasa** [demiurgosoft/maelstrom-users#4]
If you use a template engine, world will be better :dancer: 
Now seriously, it will improve your options to change views easier (and add things like add support to multiple languages)

**Comment by angrykoala** [comment]
This repo is only for an API service for users, not web client itself (the client provided is just an example), to develop the web client go to https://github.com/demiurgosoft/maelstrom-web

**Comment by iblancasa** [comment]
Ok so this folder... https://github.com/demiurgosoft/maelstrom-users/tree/master/views

**Comment by iblancasa** [comment]
Only for testing
